### ISSUE TITLE
Dont work?

### ISSUE THREAD

**Issue by swissbyte** [Neonx99/agar.io-bots-extension#4]
Hi

I have tested the script according to your guidance and steps. 
But for me it looks like it is not working. It does not anything at all. 

I have also disabled the shield... 
Has agar.io did some updates which prohibits the script from working properly?

Thanks

**Comment by neonnd** [comment]
do you see bot gui ? [ start bots button etc ]

**Comment by swissbyte** [comment]
No, i dont see the gui

**Comment by neonnd** [comment]
![Untitled](https://user-images.githubusercontent.com/48287047/73528115-e5005a00-441c-11ea-9caa-d0fafcb0e3bc.png)

well bots still work but bot gui doesn't show for some reason ill fix it later

**Comment by swissbyte** [comment]
Thank you for your reply. 
How can i verify that the bots are working? Cause when i run the script, i still can move my bubble with the mouse. And only with the mouse. If i dont move the mouse, my bubble will also not move.
